CREATE TABLE CUSTOMER (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
customer_id BIGINT,
name VARCHAR(400) NOT NULL,
surname VARCHAR(500) NULL
);

CREATE TABLE WOOD_PRODUCT (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(400) NOT NULL
);

ALTER TABLE CUSTOMER
ADD CONSTRAINT customer_product_id
FOREIGN KEY (customer_id) REFERENCES WOOD_PRODUCT(id)